ARG GO_VERSION=1
FROM golang:${GO_VERSION}-bookworm as builder

WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN go build -v -o /basher ./cmd/basher/main.go

FROM debian:bookworm

# load up some goodies for people to play with
RUN apt-get update && apt-get install -y iproute2 procps jq curl unzip git file bsdextrautils coreutils lsb-release

COPY --from=builder /basher /usr/local/bin/
CMD ["/usr/local/bin/basher"]
