# fly.toml app configuration file generated for tim-coord on 2024-12-02T12:52:20-10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tim-coord'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
